SocialLogin
lmachens/photoplay pull request #35
Opened 2021-05-27 09:33 UTC by tmh9x

2021-05-27 10:05 UTC, phlgr requested changes

2021-05-27 10:05 UTC, phlgr commented on src/app/components/Icons/FacebookIcon.tsx
> +      data-name="Facebook button"
This could be removed

2021-05-27 10:05 UTC, phlgr commented on src/app/components/SocialLogin/SocialLogin.tsx
> +import classes from './SocialLogin.module.css';
```suggestion
import styles from './SocialLogin.module.css';
```

2021-05-27 10:05 UTC, phlgr commented on src/app/components/SocialLogin/SocialLogin.tsx
> +type SocialProps = {
```suggestion
type SocialLoginProps = {
```

2021-05-27 10:05 UTC, phlgr commented on src/app/components/SocialLogin/SocialLogin.tsx
> +  icon2,
I would expect a SocialLogin component to only have one Social Login

2021-05-27 11:35 UTC, lmachens reviewed
Can you update the pull request title and description to be more describable?

2021-05-27 11:35 UTC, lmachens commented on src/app/components/Icons/FacebookIcon.tsx
> +          <stop offset="1" stop-color="#ffa90a" />
You can use CSS variables here. Take a look at:
https://github.com/lmachens/photoplay/pull/33/files#diff-67da3a784c1aad97057e7c3ea7fa3af53efc7e271207f791b8a2ccd6eeb43d96R23-R24

2021-05-27 11:35 UTC, lmachens commented on src/app/components/SocialLogin/SocialLogin.stories.tsx
> +    icon2={<GoogleIcon />}
I would love to see a list of social icons here to allow adding more services without changing the component.
wdyt about:
```suggestion
    icons={[{
      href: "https://facebook.com/photoplay",
      Icon: FacebookIcon
    }, {
      href: "https://google.com/photoplay",
      Icon: GoogleIcon 
    }]}
```

or:
```suggestion
    icons={[{
      href: "https://facebook.com/photoplay",
      icon: <FacebookIcon />
    }, {
      href: "https://google.com/photoplay",
      icon: <GoogleIcon />
    }]}
```

2021-05-30 09:19 UTC, lmachens requested changes
Good job []~(￣▽￣)~*

2021-05-30 09:19 UTC, lmachens commented on src/app/components/Icons/FacebookIcon.tsx
> +          <stop offset="1" stop-color="#ffa90a" />
See https://github.com/lmachens/photoplay/blob/main/src/app/globals.css#L14-L15
```suggestion
          <stop offset="0" stop-color="var(--primary-gradient-from)" />
          <stop offset="1" stop-color="var(--primary-gradient-to)" />
```

2021-05-30 09:19 UTC, lmachens commented on src/app/components/Icons/FacebookIcon.tsx
> +      <g id="Group_5" data-name="Group 5">
You can remove this `g` (it doesn't do anything useful)

```suggestion
```

2021-05-30 09:19 UTC, lmachens commented on src/app/components/Icons/GoogleIcon.tsx
> +        data-name="Google Logo"
```suggestion
```

2021-05-30 09:19 UTC, lmachens commented on src/app/components/SocialLogin/SocialLogin.module.css
> +  justify-self: end;
Can you explain why this is required? I would prefer to control this in the parent element to reduce the number of classes.

2021-05-30 09:19 UTC, lmachens commented on src/app/components/SocialLogin/SocialLogin.tsx
> +  icon: React.SVGProps<SVGSVGElement>;
You could be less specific here to allow `img` elements too:
```suggestion
  icon: JSX.Element;
```

2021-05-30 09:19 UTC, lmachens commented on src/app/components/SocialLogins/SocialLogins.tsx
> +        <SocialLogin icon={social.icon} link={social.link} />
Please add a `key` to help React

2021-05-31 07:41 UTC, tmh9x commented on src/app/components/Icons/FacebookIcon.tsx
> +          <stop offset="1" stop-color="#ffa90a" />
thx

2021-05-31 10:01 UTC, merged