Add register page
lmachens/photoplay pull request #38
Opened 2021-05-28 09:50 UTC by fgottesmann

We add a register page with a form component and an element to change your profile picture. We also adjusted the Registerbutton, the Backbutton and the LabeledInput component.

2021-05-28 10:16 UTC, daebert reviewed
Good work!

2021-05-28 10:16 UTC, daebert commented on src/app/Page/Register.tsx
> +            id="user-2"
Is this ID really needed for the svg?

2021-05-28 10:16 UTC, daebert commented on src/app/Page/Register.tsx
> +            id="user-2"
```suggestion
 
```

2021-05-28 10:19 UTC, SGierszewski reviewed
Good job!! 🥳

2021-05-28 10:19 UTC, SGierszewski commented on src/app/Page/Register.module.css
> +  margin: 0% 7% 0% 7%;
I think this can be shortened to margin: 0% 7%;

2021-05-28 10:20 UTC, roabram requested changes
Good Job :-)

2021-05-28 10:20 UTC, roabram commented on src/app/Page/Register.module.css
> +  margin: 0% 7% 0% 7%;
```suggestion
  margin: 0% 7%;
```

2021-05-28 10:20 UTC, roabram commented on src/app/Page/Register.module.css
> +  margin-bottom: 10%;
Maybe it would be better to use grid-gap instead of margin/ margin-bottom.

2021-05-28 10:20 UTC, roabram commented on src/app/Page/Register.stories.tsx
> +  component: Register,
```suggestion
  component: Register,
  parameter: {
     layout: "fullscreen",
     },
```

2021-05-28 10:20 UTC, roabram commented on src/app/Page/Register.tsx
> +        <svg
Maybe it's better to outsource the svg into a single file.

2021-05-28 10:20 UTC, roabram commented on src/app/components/Button/Button.module.css
> +  border-radius: 12px;
```suggestion
  border-radius: 0.75em;
```

2021-05-28 10:27 UTC, Maurizio-F reviewed
Good job! 💯

2021-05-28 10:27 UTC, Maurizio-F commented on src/app/Page/Register.tsx
> +        <svg
Create own component for svg? ;)

2021-05-28 10:27 UTC, Maurizio-F commented on src/app/Page/Register.tsx
> +          </defs>
Code not needed. Gradient is defined in global.css.

2021-05-28 10:27 UTC, Maurizio-F commented on src/app/Page/Register.tsx
> +            id="user-2"
Id not needed.

2021-05-28 10:27 UTC, Dev-dfm reviewed
lgtm 💯

2021-05-28 11:36 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +            id="user-2"
Removed this ID, thanks

2021-05-28 11:37 UTC, fgottesmann commented on src/app/Page/Register.module.css
> +  margin: 0% 7% 0% 7%;
Removed the unused CSS, thank you

2021-05-28 11:42 UTC, fgottesmann commented on src/app/Page/Register.stories.tsx
> +  component: Register,
Requested changes were made. Thanks

2021-05-28 11:51 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +        <svg
We outsourced the SVG to a separate file

2021-05-28 11:51 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +        <svg
Already done ;)

2021-05-28 11:53 UTC, fgottesmann commented on src/app/components/Button/Button.module.css
> +  border-radius: 12px;
Changed 12px to 0.8em

2021-05-28 11:57 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +            id="user-2"
Has been removed.

2021-05-28 15:33 UTC, phlgr requested changes

2021-05-28 15:33 UTC, phlgr commented on src/app/Page/Register.tsx
> +    event.preventDefault();
```suggestion
    event.preventDefault();
    alert(`${firstName} submitted`);
```

2021-05-28 15:33 UTC, phlgr commented on src/app/components/Icons/ProfilePictureIcon.tsx
> +"
```suggestion
            stop-color="var(--primary-gradient-to)"
```

2021-05-28 15:33 UTC, phlgr commented on src/app/components/LabeledInput/LabeledInput.tsx
>          placeholder={`${placeholder}` + ' here'}
```suggestion
        placeholder={`${placeholder} here`}
```

2021-05-30 09:23 UTC, lmachens requested changes
(*^▽^*)

2021-05-30 09:23 UTC, lmachens commented on src/app/Page/Register.tsx
> +          <form className={styles.registerForm__label} onSubmit={handleSubmit}>
The `div` has the class `registerForm__form`, the `form` has the class `registerForm__label`.
I would expect that the `form` has `registerForm__form`.

In addition, you don't need the `div` here if you style the form.

2021-05-30 09:23 UTC, lmachens commented on src/app/Page/Register.module.css
> +.registerForm__SVG {
Is it important that it's a `SVG`? I would prefer `registerForm__icon`

2021-05-31 07:08 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +    event.preventDefault();
Done.

2021-05-31 07:10 UTC, fgottesmann commented on src/app/components/Icons/ProfilePictureIcon.tsx
> +"
Requested changes were made

2021-05-31 07:12 UTC, fgottesmann commented on src/app/components/LabeledInput/LabeledInput.tsx
>          placeholder={`${placeholder}` + ' here'}
Changed

2021-05-31 08:42 UTC, fgottesmann commented on src/app/Page/Register.tsx
> +          <form className={styles.registerForm__label} onSubmit={handleSubmit}>
We delete the `div `and rename the form to `registerForm__form`

2021-05-31 08:48 UTC, fgottesmann commented on src/app/Page/Register.module.css
> +.registerForm__SVG {
Naming has been changed

2021-05-31 08:51 UTC, fgottesmann commented on src/app/Page/Register.module.css
> +  margin-bottom: 10%;
Alright, we changed `margin-bottom` to `padding-bottom`. We decided that we don't want to use grid gap.

2021-05-31 09:56 UTC, merged