✨ Add Profile page
lmachens/photoplay pull request #39
Opened 2021-05-28 11:55 UTC by dhnazarenko

fixes #14

This pull reguest requires an update after navigation menu component finished

2021-05-30 09:25 UTC, lmachens approved these changes
(～￣▽￣)～

2021-05-31 07:18 UTC, tmh9x approved these changes

2021-05-31 07:24 UTC, Dev-dfm reviewed
great work! 💯

2021-05-31 07:34 UTC, daebert reviewed
Good work!

2021-05-31 07:36 UTC, SGierszewski approved these changes
Good job!! 🥳

2021-05-31 07:36 UTC, JGieseWeb approved these changes

2021-05-31 07:41 UTC, lajanzen requested changes
Looks good to us, just a small change! 🤓

2021-05-31 07:41 UTC, lajanzen commented on src/app/pages/Profile/Profile.module.css
> +  font-weight: 400;
Isn't this the standard font-weight?

2021-05-31 07:42 UTC, jujuzitroni reviewed
good job! 
you could add two components to the Profile page, this would reduce the amount of imports you need right now.

2021-05-31 07:42 UTC, jujuzitroni commented on src/app/pages/Profile/Profile.tsx
> +      <footer className={styles.footer}>
a NavBar component is now available and can be used here.

2021-05-31 07:42 UTC, jujuzitroni commented on src/app/pages/Profile/Profile.tsx
> +        <ProfileMenuBar link="#" icon={<AccountIcon />} text="Account" />
maybe add a profile menu component to summarise the ProfileMenuBar components into.

2021-05-31 07:42 UTC, jujuzitroni commented on src/app/pages/Profile/Profile.tsx
> +        <h1 className={styles.profileName}>Dieter Bohlen</h1>
h1 and span should accept dynamic input

2021-05-31 07:42 UTC, jujuzitroni commented on src/app/pages/Profile/Profile.stories.tsx
> +export const Default = (): JSX.Element => <Profile />;
can you add another story maybe with the other modern talking member? :)

2021-05-31 08:51 UTC, dhnazarenko commented on src/app/pages/Profile/Profile.tsx
> +        <h1 className={styles.profileName}>Dieter Bohlen</h1>
h1 and span are integrated with the api.

2021-05-31 08:52 UTC, dhnazarenko commented on src/app/pages/Profile/Profile.tsx
> +        <ProfileMenuBar link="#" icon={<AccountIcon />} text="Account" />
We have discussed that this component will not be created for the time being.

2021-05-31 08:54 UTC, dhnazarenko commented on src/app/pages/Profile/Profile.tsx
> +      <footer className={styles.footer}>
See description. Componente is built in today.

2021-05-31 08:58 UTC, dhnazarenko commented on src/app/pages/Profile/Profile.module.css
> +  font-weight: 400;
Thanks i removed it.

2021-05-31 09:16 UTC, dhnazarenko commented on src/app/pages/Profile/Profile.stories.tsx
> +export const Default = (): JSX.Element => <Profile />;
We discussed in the group that it is not necessary. Thanks for your review! 🚀

2021-05-31 09:39 UTC, merged