Add seriesCard
lmachens/photoplay pull request #42
Opened 2021-05-28 13:13 UTC by infoucarsinan

Create seriesCard

2021-05-30 09:35 UTC, lmachens requested changes
Good job (oﾟvﾟ)ノ. Can you link the related issue in the pull request description?

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  background: transparent;
I don't think this is required

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  grid-column: 2/3;
Are you sure you need this?

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  font-weight: 400;
I guess this is the default font-weight -> You can remove it.

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.tsx
> +    <div className={styles.container}>
I like to see a semantic tag here like `article`.

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.tsx
> +      <img className={styles.img} src={imgSrc} />
Don't forget about `alt`.

2021-05-30 09:35 UTC, lmachens commented on src/app/components/SeriesCard/SeriesCard.module.css
> +.headline {
This is not exactly BEM like. 
Maybe this is better?
```suggestion
.seriesInfo__headline {
```

2021-05-31 07:25 UTC, SGierszewski approved these changes
Good job!! 🥳

2021-05-31 07:26 UTC, MaxMuecket approved these changes
well done👌

2021-05-31 07:40 UTC, J-Bannach commented
👍

2021-05-31 08:50 UTC, infoucarsinan commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  background: transparent;
ok

2021-05-31 08:50 UTC, infoucarsinan commented on src/app/components/SeriesCard/SeriesCard.module.css
> +.headline {
ok

2021-05-31 08:51 UTC, infoucarsinan commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  font-weight: 400;
ok

2021-05-31 08:52 UTC, infoucarsinan commented on src/app/components/SeriesCard/SeriesCard.tsx
> +    <div className={styles.container}>
ok

2021-05-31 08:54 UTC, infoucarsinan commented on src/app/components/SeriesCard/SeriesCard.module.css
> +  grid-column: 2/3;
ok

2021-05-31 09:37 UTC, merged