:sparkles: Add Cast Page
lmachens/photoplay pull request #43
Opened 2021-05-28 13:28 UTC by daebert

globals CSS not working,
also: when we set a background color in our module.css, the image disappears

2021-05-28 16:12 UTC, phlgr requested changes

2021-05-28 16:12 UTC, phlgr commented on src/app/components/MovieCard/MovieCard.tsx
> +    </div>
```suggestion
      <img className={styles.image} src={imgSrc} alt="" />
```

2021-05-28 16:12 UTC, phlgr commented on src/app/pages/Cast/Cast.tsx
> +        <BackButton></BackButton>
```suggestion
        <BackButton />
```

2021-05-30 09:58 UTC, lmachens reviewed
（*＾-＾*）

2021-05-30 09:58 UTC, lmachens commented on src/app/components/MovieCard/MovieCard.tsx
> +      <img className={styles.image} src={imgSrc} alt="" />
An `alt` could make sense here

2021-05-30 09:58 UTC, lmachens commented on src/app/pages/Cast/Cast.module.css
> +}
Why is the scrollbar not displayed?

2021-05-31 07:15 UTC, tmh9x approved these changes

2021-05-31 07:22 UTC, MaxMuecket requested changes
Looks good. Just a small change 😉
From BR 2

2021-05-31 07:22 UTC, MaxMuecket commented on src/app/pages/Cast/Cast.module.css
> +  grid-template-columns: 1fr 1fr 1fr 1fr;
```suggestion
  grid-template-columns: repeat(4, 1fr);
```

2021-05-31 07:40 UTC, Dev-dfm reviewed
lgtm 🚀

2021-05-31 09:08 UTC, daebert commented on src/app/pages/Cast/Cast.module.css
> +}
To us, it seems very common on mobile-first applications to not have a scrollbar. The user will see that it is scrollable from the design of the page.

2021-05-31 09:09 UTC, daebert commented
> （_＾-＾_）
> Could you link the related issue?

Checked it intitally. Unfortunmately there is no issue for this topic.

2021-05-31 10:39 UTC, merged