✨  Add TV show details page
lmachens/photoplay pull request #44
Opened 2021-05-28 14:04 UTC by Dev-dfm

Add components and styling to TV show details page for issue#4

2021-05-30 10:07 UTC, lmachens requested changes
Good job \^o^/
This pull request adds `NavBar` which is part of other pages too. Please add a note about this in the description.

2021-05-30 10:07 UTC, lmachens commented on src/app/pages/TVShowDetails/TVShowDetails.module.css
> +footer {
This targets every `footer`.

2021-05-31 07:10 UTC, roabram approved these changes
Looks good 👌
BR2

2021-05-31 07:11 UTC, tmh9x approved these changes

2021-05-31 07:15 UTC, daebert approved these changes
Good job!

2021-05-31 07:16 UTC, SGierszewski approved these changes
Good job!! 🥳

2021-05-31 07:19 UTC, SGierszewski approved these changes
Good job!! 🥳

2021-05-31 07:22 UTC, dhnazarenko approved these changes
lgtm 🚀

2021-05-31 08:38 UTC, merged