✨ Add mapping for popular Movies from API
lmachens/photoplay pull request #71
Opened 2021-06-02 14:00 UTC by daebert

fixes #62

2021-06-02 14:34 UTC, JGieseWeb approved these changes
Good job 🎯

2021-06-02 15:18 UTC, lmachens requested changes
(^///^)

2021-06-02 15:18 UTC, lmachens commented on src/app/pages/Homescreen/Homescreen.tsx
> +import { pathToFileURL } from 'url';
This seems to be unused

2021-06-02 15:18 UTC, lmachens commented on src/app/pages/Homescreen/Homescreen.tsx
> +            imgSrc={popularMovie.posterPath || ''}
Maybe find a good placeholder if `posterPath` is not available.

2021-06-02 15:22 UTC, daebert commented on src/app/pages/Homescreen/Homescreen.tsx
> +import { pathToFileURL } from 'url';
Thank you. Done!

2021-06-03 07:01 UTC, dhnazarenko approved these changes
lgtm 🚀

2021-06-03 07:46 UTC, Dev-dfm reviewed
lgtm 🚀

2021-06-03 08:13 UTC, lajanzen approved these changes
Looks great!

2021-06-03 08:20 UTC, Niklas-Schaefers approved these changes
lgtm 🚀

2021-06-03 08:46 UTC, l-goede approved these changes
very good work!

2021-06-03 08:55 UTC, Dev-dfm approved these changes
lgtm 🚀

2021-06-03 09:07 UTC, tmh9x approved these changes

2021-06-03 09:07 UTC, roabram approved these changes
lgtm

2021-06-03 09:07 UTC, infoucarsinan approved these changes

2021-06-03 09:08 UTC, J-Bannach approved these changes

2021-06-03 09:08 UTC, JGieseWeb approved these changes
lgtm 👍

2021-06-03 09:09 UTC, merged